spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME} # <-- comes from SSM secret
    password: ${SPRING_DATASOURCE_PASSWORD} # <-- comes from SSM secret
